import { Metadata, ParsedData, PromptTemplate, PromptOptions } from './types';
import { formatNumber, formatPercent, truncate, obfuscateString, anonymizeValue, resetAnonymization } from './utils';
import { tPrompt } from './i18n';
import { useAppStore } from '../hooks/store';

export function generatePrompt(metadata: Metadata, parsedData: ParsedData, options: PromptOptions = {}): string {
    const {
        mode = 'privacy',
        userContext = '',
        action = null
    } = options;
    const lang = useAppStore.getState().language || 'vi';

    const parts: string[] = [];

    parts.push(tPrompt('prompt.analysisTitle'));
    parts.push('');

    parts.push(tPrompt('prompt.metaContext'));
    parts.push('');
    parts.push(buildStructureSection(metadata, parsedData as any, lang));
    parts.push('');

    parts.push(tPrompt('prompt.colDetails'));
    parts.push('');
    parts.push(buildColumnsTable(metadata, mode === 'privacy', lang));
    parts.push('');

    const numericCols = metadata.columns.filter(c => c.stats);
    if (numericCols.length > 0) {
        parts.push(tPrompt('prompt.numStats'));
        parts.push('');
        parts.push(buildStatsTable(numericCols, lang));
        parts.push('');
    }

    if (metadata.insights && metadata.insights.length > 0) {
        parts.push(tPrompt('prompt.issues'));
        parts.push('');
        parts.push(buildIssuesSection(metadata.insights));
        parts.push('');
    }

    if (metadata.relationships && metadata.relationships.length > 0) {
        parts.push(tPrompt('prompt.relationships'));
        parts.push('');
        metadata.relationships.forEach((r, i) => {
            parts.push(`${i + 1}. **${r.from}** → **${r.to}** (${r.type})`);
        });
        parts.push('');
    }

    if (mode === 'sample' || mode === 'full') {
        parts.push(tPrompt('prompt.sampleData'));
        parts.push('');
        if (mode === 'sample') {
            parts.push(tPrompt('prompt.sampleAnonymized'));
            parts.push('');
            parts.push(buildSampleData(parsedData, metadata, 5, true));
        } else {
            parts.push(tPrompt('prompt.sampleFull'));
            parts.push('');
            const maxRows = Math.min(parsedData.totalRows, 200);
            parts.push(buildSampleData(parsedData, metadata, maxRows, false, lang));
            if (parsedData.totalRows > 200) {
                parts.push(`\n${tPrompt('prompt.showingRows')} 200/${parsedData.totalRows} ${tPrompt('prompt.rowsFirst')}`);
            }
        }
        parts.push('');
    }

    if (metadata.readiness) {
        parts.push(tPrompt('prompt.readiness'));
        parts.push('');
        const readiness: any = metadata.readiness;
        for (const [, item] of Object.entries(readiness)) {
            if (typeof item === 'object' && item !== null && 'status' in item) {
                const itemObj = item as any;
                const statusMap: any = { ready: '✅', warning: '⚠️', not_ready: '❌' };
                parts.push(`- ${statusMap[itemObj.status] || '❓'} **${itemObj.label}**: ${itemObj.note}`);
            }
        }
        parts.push('');
    }

    parts.push('---');
    parts.push('');

    if (action && action.instruction) {
        parts.push(tPrompt('prompt.userSpecialReq').replace(':', ` (${action.label}):`));
        parts.push(`> ${action.instruction}`);
        parts.push('');
    }

    if (userContext && userContext.trim()) {
        if (!action) {
            parts.push(tPrompt('prompt.userSpecialReq'));
        }
        parts.push(`> ${userContext.trim()}`);
        parts.push('');
    }

    if (!userContext && !action) {
        parts.push(tPrompt('prompt.defaultInstructions'));
    } else if (action || userContext) {
        // Nếu có hành động đặc biệt, vẫn nhắc nhở chèn ảnh nếu được
        parts.push(tPrompt('prompt.quickchartReminder'));
    }

    parts.push('');
    parts.push('---');
    parts.push(tPrompt('prompt.mandatoryCommands'));
    parts.push(`\n*${lang === 'en' ? 'Prompt generated by DataLens v1.0 | Mode:' : 'Prompt được tạo bởi DataLens v1.0 | Mode:'} ${mode === 'privacy' ? (lang === 'en' ? '🛡️ Privacy' : '🛡️ Privacy') : mode === 'sample' ? (lang === 'en' ? '📊 Sample' : '📊 Sample') : (lang === 'en' ? '🔓 Full' : '🔓 Full')} | ${new Date().toLocaleString(lang === 'en' ? 'en-US' : 'vi-VN')}*`);

    return parts.join('\n');
}

export function buildStructureSection(metadata: Metadata, parsedData: any, lang: string = 'vi'): string {
    const lines: string[] = [];
    const fileName = parsedData.fileName || 'unknown';
    const ext = fileName.includes('.') ? fileName.split('.').pop().toLowerCase() : 'unknown';
    const isExcel = ['xlsx', 'xls', 'xlsb', 'xlsm'].includes(ext);

    lines.push(`${tPrompt('prompt.metaSourceFile', lang as any)}${fileName}`);
    lines.push(`${tPrompt('prompt.metaFormat', lang as any)}FILE ${isExcel ? 'EXCEL' : ext.toUpperCase()}${tPrompt('prompt.metaFormatNote', lang as any)}`);

    if (parsedData.sheetNames && parsedData.sheetNames.length > 1) {
        lines.push(`${tPrompt('prompt.metaSheets', lang as any)}${parsedData.sheetNames.length}${tPrompt('prompt.metaActiveSheet', lang as any)}${parsedData.activeSheet}"`);
    }

    let structureWarning: string[] = [];
    if (parsedData.skipRows && parsedData.skipRows > 0) {
        let text = String(tPrompt('prompt.metaSkipRows', lang as any)).replace('{0}', String(parsedData.skipRows + 1)).replace('{1}', String(parsedData.skipRows));
        structureWarning.push(text);
    }
    if (parsedData.skipCols && parsedData.skipCols > 0) {
        let text = String(tPrompt('prompt.metaSkipCols', lang as any)).replace('{0}', String(parsedData.skipCols + 1)).replace('{1}', String(parsedData.skipCols));
        structureWarning.push(text);
    }

    if (structureWarning.length > 0) {
        lines.push(`${tPrompt('prompt.metaStructureWarning', lang as any)} ${structureWarning.join(' VÀ ')}.`);
    }

    lines.push(`${tPrompt('prompt.metaTotalRows', lang as any)}${formatNumber(metadata.totalRows)}${tPrompt('prompt.metaTotalCols', lang as any)}${metadata.totalCols}`);
    lines.push(`${tPrompt('prompt.metaQualityScore', lang as any)}${metadata.qualityScore || 0}/100`);

    const typeDist: Record<string, number> = {};
    metadata.columns.forEach(c => {
        typeDist[c.dataType] = (typeDist[c.dataType] || 0) + 1;
    });
    const typeStr = Object.entries(typeDist)
        .map(([type, count]) => `${type} (${count})`)
        .join(', ');
    lines.push(`${tPrompt('prompt.metaTypeDist', lang as any)}${typeStr}`);

    const piiCols = metadata.columns.filter(c => c.isPII);
    if (piiCols.length > 0) {
        lines.push(`${tPrompt('prompt.metaPII', lang as any)}${piiCols.map(c => c.name).join(', ')}`);
    }

    return lines.join('\n');
}

export function buildColumnsTable(metadata: Metadata, privacyShield = false, lang: string = 'vi'): string {
    const lines: string[] = [];
    lines.push(tPrompt('prompt.tableHeadersCols1', lang as any));
    lines.push(tPrompt('prompt.tableHeadersCols2', lang as any));

    metadata.columns.forEach((col, i) => {
        let samples = '';
        if (col.isPII) {
            samples = tPrompt('prompt.tableSamplesPII', lang as any);
        } else if (privacyShield) {
            samples = (col.sampleValues || []).slice(0, 3).map(v => obfuscateString(truncate(v, 15))).join(', ');
        } else {
            samples = (col.sampleValues || []).slice(0, 3).map(v => truncate(v, 15)).join(', ');
        }

        lines.push(
            `| ${i + 1} | ${col.name} | ${col.dataType} | ${formatPercent(col.nullPercent)} | ${formatNumber(col.uniqueCount)} | ${samples} |`
        );
    });

    return lines.join('\n');
}

export function buildStatsTable(numericCols: any[], lang: string = 'vi'): string {
    const lines: string[] = [];
    lines.push(tPrompt('prompt.tableHeadersStats1', lang as any));
    lines.push(tPrompt('prompt.tableHeadersStats2', lang as any));

    numericCols.forEach(col => {
        const s = col.stats;
        lines.push(
            `| ${col.name} | ${formatNumber(s.min)} | ${formatNumber(s.max)} | ${formatNumber(s.mean, 1)} | ${formatNumber(s.median, 1)} | ${formatNumber(s.stddev, 1)} |`
        );
    });

    return lines.join('\n');
}

export function buildIssuesSection(insights: any[], lang: string = 'vi'): string {
    const severityIcons: any = { high: '🔴', medium: '🟡', low: '🟢', info: 'ℹ️' };
    return insights.map((insight, i) => {
        return `${i + 1}. ${severityIcons[insight.severity] || '•'} **${insight.title}**\n   ${insight.description}\n   → *${lang === 'en' ? 'Action/Recommendation' : insight.action || insight.recommendation}*`;
    }).join('\n\n');
}

export function buildSampleData(parsedData: ParsedData, metadata: Metadata, numRows: number, anonymize: boolean, lang: string = 'vi'): string {
    const headers = parsedData.headers;
    const sampleRows = parsedData.rows.slice(0, numRows);

    if (sampleRows.length === 0) return tPrompt('prompt.sampleNoData', lang as any);

    resetAnonymization();

    const lines: string[] = [];
    lines.push('| ' + headers.join(' | ') + ' |');
    lines.push('| ' + headers.map(() => '---').join(' | ') + ' |');

    sampleRows.forEach((row: any[]) => {
        const cells = headers.map((h, colIdx) => {
            let val = row[colIdx];
            if (val == null || val === '') return '';

            if (anonymize && metadata.columns[colIdx]?.isPII) {
                val = anonymizeValue(val, h, metadata.columns[colIdx].dataType);
            }

            return truncate(String(val), 25);
        });
        lines.push('| ' + cells.join(' | ') + ' |');
    });

    return lines.join('\n');
}

export function applyTemplate(template: PromptTemplate, metadata: Metadata, parsedData: ParsedData, privacyShield = true, lang: string = 'vi'): string {
    if (!template || !template.prompt) return '';

    let prompt = template.prompt;

    prompt = prompt.replace(/\{fileName\}/g, (parsedData as any).fileName || 'unknown');
    prompt = prompt.replace(/\{totalRows\}/g, formatNumber(metadata.totalRows));
    prompt = prompt.replace(/\{totalCols\}/g, metadata.totalCols.toString());
    prompt = prompt.replace(/\{qualityScore\}/g, (metadata.qualityScore || 0).toString());
    prompt = prompt.replace(/\{columnList\}/g, metadata.columns.map(c => c.name).join(', '));

    prompt = prompt.replace(/\{numericCols\}/g,
        metadata.columns.filter(c => c.dataType === 'number' || c.dataType === 'currency').map(c => c.name).join(', ') || 'N/A'
    );
    prompt = prompt.replace(/\{dateCols\}/g,
        metadata.columns.filter(c => c.dataType === 'date').map(c => c.name).join(', ') || 'N/A'
    );
    prompt = prompt.replace(/\{categoricalCols\}/g,
        metadata.columns.filter(c => c.issues && c.issues.some((i: any) => i.type === 'likely_categorical')).map(c => c.name).join(', ') || 'N/A'
    );

    let metaText = buildStructureSection(metadata, parsedData, lang) + '\n\n' + buildColumnsTable(metadata, privacyShield, lang);

    if (metadata.insights && metadata.insights.length > 0) {
        metaText += tPrompt('prompt.issueHeader', lang as any) + '\n' + buildIssuesSection(metadata.insights, lang);
    }

    const columnsWithAnomalies = metadata.columns.filter(c => c.issues && c.issues.some((i: any) => i.examples && i.examples.length > 0));
    if (columnsWithAnomalies.length > 0) {
        metaText += tPrompt('prompt.colIssuesHeader', lang as any) + '\n';
        columnsWithAnomalies.forEach(col => {
            metaText += String(tPrompt('prompt.colNameTitle', lang as any)).replace('{0}', col.name);
            col.issues.filter((i: any) => i.examples && i.examples.length > 0).forEach((issue: any) => {
                metaText += String(tPrompt('prompt.issueError', lang as any)).replace('{0}', issue.detail);
                if (privacyShield) {
                    const obfExamples = issue.examples.map((ex: any) => obfuscateString(String(ex)));
                    metaText += String(tPrompt('prompt.issueErrorObf', lang as any)).replace('{0}', obfExamples.join('`, `'));
                } else {
                    metaText += String(tPrompt('prompt.issueErrorRaw', lang as any)).replace('{0}', issue.examples.join('`, `'));
                }
            });
        });
    }

    prompt = prompt.replace(/\{metadataBlock\}/g, metaText);

    prompt += '\n\n---\n';
    prompt += tPrompt('prompt.mandatoryCommands', lang as any);

    return prompt;
}

export function detectDomain(metadata: Metadata): { domain: string; icon: string; score: number } {
    if (!metadata || !metadata.columns) return { domain: 'Tổng hợp (General)', icon: '📊', score: 0 };

    const colNames = metadata.columns.map(c => c.name.toLowerCase());
    const rules = [
        {
            domain: 'Sales & Retail',
            icon: '🛒',
            keywords: ['sales', 'doanh thu', 'price', 'giá', 'order', 'đơn hàng', 'customer', 'khách hàng', 'quantity', 'số lượng', 'product', 'sản phẩm', 'discount', 'chiết khấu', 'revenue', 'lợi nhuận', 'profit', 'store', 'cửa hàng']
        },
        {
            domain: 'Nhân sự (HR)',
            icon: '👥',
            keywords: ['employee', 'nhân viên', 'salary', 'lương', 'department', 'phòng ban', 'hire', 'tuyển dụng', 'manager', 'turnover', 'nghỉ việc', 'performance', 'đánh giá', 'age', 'tuổi', 'gender', 'giới tính', 'role', 'chức vụ']
        },
        {
            domain: 'Giáo dục (Education)',
            icon: '🎓',
            keywords: ['student', 'học sinh', 'sinh viên', 'score', 'điểm', 'grade', 'class', 'lớp', 'course', 'khóa học', 'faculty', 'khoa', 'teacher', 'giáo viên', 'exam', 'kỳ thi']
        },
        {
            domain: 'Tài chính (Finance)',
            icon: '💰',
            keywords: ['account', 'tài khoản', 'balance', 'số dư', 'transaction', 'giao dịch', 'expense', 'chi phí', 'budget', 'ngân sách', 'tax', 'thuế', 'loan', 'khoản vay', 'interest', 'lãi suất']
        },
        {
            domain: 'Healthcare & Medical',
            icon: '🏥',
            keywords: ['patient', 'bệnh nhân', 'doctor', 'bác sĩ', 'diagnosis', 'chẩn đoán', 'treatment', 'điều trị', 'blood', 'huyết áp', 'disease', 'bệnh', 'hospital', 'bệnh viện', 'symptom', 'triệu chứng']
        },
        {
            domain: 'Marketing',
            icon: '📈',
            keywords: ['campaign', 'chiến dịch', 'click', 'impression', 'lượt xem', 'conversion', 'chuyển đổi', 'cpc', 'roi', 'ad', 'quảng cáo', 'channel', 'kênh', 'traffic', 'truy cập']
        }
    ];

    let maxScore = 0;
    let bestMatch = rules[0];

    for (const rule of rules) {
        let score = 0;
        for (const col of colNames) {
            for (const kw of rule.keywords) {
                if (col.includes(kw)) {
                    score += 1;
                    break;
                }
            }
        }
        if (score > maxScore) {
            maxScore = score;
            bestMatch = rule;
        }
    }

    if (maxScore >= 2) {
        return { domain: bestMatch.domain, icon: bestMatch.icon, score: maxScore };
    }

    return { domain: 'Tổng hợp (General)', icon: '📊', score: maxScore };
}

export function getSuggestedActions(domainInfo: { domain: string }): any[] {
    const lang = useAppStore.getState().language || 'vi';

    if (lang === 'en') {
        const defaultActions = [
            { id: 'general_1', label: 'Insight Summary', icon: '💡', instruction: 'Please summarize the most important insights from this dataset in 3-5 bullet points.' },
            { id: 'general_2', label: 'Risk/Anomaly Analysis', icon: '⚠️', instruction: 'Please find and analyze anomalies, outliers, or potential risks in the data.' },
            { id: 'general_3', label: 'Python Visualizations', icon: '📈', instruction: 'Please write Python code (Matplotlib/Seaborn) to draw the most insightful visualizations for this dataset.' },
        ];

        const domainActions: Record<string, any[]> = {
            'Sales & Retail': [
                { id: 'sales_1', label: 'Revenue Analysis', icon: '💰', instruction: 'Analyze revenue and profit trends, find products or customer segments that provide the highest value.' },
                { id: 'sales_2', label: 'Trend Forecasting', icon: '📈', instruction: 'Draw a sales trend chart over time and provide a short-term forecast.' },
                { id: 'sales_3', label: 'Customer Segmentation (RFM)', icon: '👥', instruction: 'Based on the data, segment customers and evaluate their loyalty (RFM model if possible).' }
            ],
            'Nhân sự (HR)': [
                { id: 'hr_1', label: 'Salary Cost Evaluation', icon: '💵', instruction: 'Analyze the salary cost structure by department, position, and experience.' },
                { id: 'hr_2', label: 'Turnover Rate', icon: '🚪', instruction: 'Evaluate employee turnover rate and find the main causes if possible.' },
                { id: 'hr_3', label: 'Diversity & Demographics', icon: '🌍', instruction: 'Analyze the distribution of age, gender, and seniority of employees.' }
            ],
            'Giáo dục (Education)': [
                { id: 'edu_1', label: 'Score Distribution', icon: '📊', instruction: 'Draw the score distribution for students, evaluate pass/fail rates, and categorize academic performance.' },
                { id: 'edu_2', label: 'Result Affecting Factors', icon: '🎯', instruction: 'Explore the factors (e.g., attendance, gender, subject) that most affect grades.' },
                { id: 'edu_3', label: 'Training Report', icon: '📋', instruction: 'Summarize the capability assessment and learning progress of the students.' }
            ],
            'Tài chính (Finance)': [
                { id: 'fin_1', label: 'Income & Expense Report', icon: '📉', instruction: 'Analyze Cash flow, compare total income and total expenses by category.' },
                { id: 'fin_2', label: 'Budget Alert', icon: '🚨', instruction: 'Check if any category is over budget or if there are abnormal expenses.' },
                { id: 'fin_3', label: 'Profit Analysis', icon: '💎', instruction: 'Evaluate profit margins, ROI, and financial health indicators.' }
            ],
            'Healthcare & Medical': [
                { id: 'health_1', label: 'Disease Distribution', icon: '🦠', instruction: 'Statistically analyze and visualize the proportion of common disease groups or symptoms in the dataset.' },
                { id: 'health_2', label: 'Treatment Efficiency', icon: '💊', instruction: 'Evaluate hospital stay times, recovery rates, and the effectiveness of treatments.' },
                { id: 'health_3', label: 'Patient Demographics', icon: '👥', instruction: 'Analyze the relationship between age, gender, and specific disease groups.' }
            ],
            'Marketing': [
                { id: 'mkt_1', label: 'Channel Efficiency', icon: '🎯', instruction: 'Compare efficiency (ROI, CPC, Conversion Rate) between marketing/ad channels.' },
                { id: 'mkt_2', label: 'Traffic Analysis', icon: '🌐', instruction: 'Analyze traffic volume over time and referral sources.' },
                { id: 'mkt_3', label: 'Budget Optimization', icon: '💰', instruction: 'Provide recommendations for reallocating marketing budgets based on actual campaign performance.' }
            ]
        };

        return domainActions[domainInfo.domain] || defaultActions;
    }

    const defaultActions = [
        { id: 'general_1', label: 'Tóm tắt Insight', icon: '💡', instruction: 'Hãy tóm tắt các insight quan trọng nhất từ tập dữ liệu này trong 3-5 gạch đầu dòng.' },
        { id: 'general_2', label: 'Phân tích Rủi ro/Bất thường', icon: '⚠️', instruction: 'Hãy tìm và phân tích các điểm bất thường, outliers, hoặc rủi ro tiềm ẩn trong dữ liệu.' },
        { id: 'general_3', label: 'Biểu đồ trực quan Python', icon: '📈', instruction: 'Hãy viết code Python (Matplotlib/Seaborn) để vẽ các biểu đồ trực quan nhất cho tập dữ liệu này.' },
    ];

    const domainActions: Record<string, any[]> = {
        'Sales & Retail': [
            { id: 'sales_1', label: 'Phân tích Doanh thu', icon: '💰', instruction: 'Hãy phân tích xu hướng doanh thu và lợi nhuận, tìm ra sản phẩm hoặc nhóm khách hàng mang lại giá trị cao nhất.' },
            { id: 'sales_2', label: 'Dự báo xu hướng', icon: '📈', instruction: 'Vẽ biểu đồ xu hướng doanh số theo thời gian và đưa ra dự báo ngắn hạn.' },
            { id: 'sales_3', label: 'Phân tích khách hàng (RFM)', icon: '👥', instruction: 'Dựa trên dữ liệu, hãy phân tập khách hàng và đánh giá mức độ trung thành của họ (RFM model nếu có thể).' }
        ],
        'Nhân sự (HR)': [
            { id: 'hr_1', label: 'Đánh giá chi phí lương', icon: '💵', instruction: 'Hãy phân tích cấu trúc chi phí lương theo phòng ban, vị trí và kinh nghiệm.' },
            { id: 'hr_2', label: 'Chỉ số biến động (Turnover)', icon: '🚪', instruction: 'Đánh giá tỷ lệ nghỉ việc, biến động nhân sự và tìm ra nguyên nhân chính nếu có thể.' },
            { id: 'hr_3', label: 'Đa dạng & Nhân khẩu học', icon: '🌍', instruction: 'Phân tích phân bố độ tuổi, giới tính và thâm niên của nhân viên.' }
        ],
        'Giáo dục (Education)': [
            { id: 'edu_1', label: 'Phân tích phổ điểm', icon: '📊', instruction: 'Vẽ phổ điểm sinh viên/học sinh, đánh giá tỷ lệ đỗ/trượt và phân loại học lực.' },
            { id: 'edu_2', label: 'Yếu tố ảnh hưởng kết quả', icon: '🎯', instruction: 'Khám phá các yếu tố (như chuyên cần, giới tính, môn học) ảnh hưởng lớn nhất đến điểm số.' },
            { id: 'edu_3', label: 'Báo cáo rèn luyện', icon: '📋', instruction: 'Tổng hợp đánh giá năng lực và quá trình học tập của học viên.' }
        ],
        'Tài chính (Finance)': [
            { id: 'fin_1', label: 'Báo cáo Thu Chi', icon: '📉', instruction: 'Phân tích dòng tiền (Cash flow), so sánh tổng thu và tổng chi theo từng hạng mục.' },
            { id: 'fin_2', label: 'Cảnh báo Ngân sách', icon: '🚨', instruction: 'Kiểm tra xem có hạng mục nào đang vượt ngân sách hoặc có chi phí bất thường không.' },
            { id: 'fin_3', label: 'Phân tích Lợi nhuận', icon: '💎', instruction: 'Đánh giá biên lợi nhuận, ROI và các chỉ số sức khỏe tài chính.' }
        ],
        'Healthcare & Medical': [
            { id: 'health_1', label: 'Phân bố Bệnh lý', icon: '🦠', instruction: 'Thống kê và trực quan hóa tỷ lệ các nhóm bệnh hoặc triệu chứng phổ biến trong tập dữ liệu.' },
            { id: 'health_2', label: 'Hiệu quả Điều trị', icon: '💊', instruction: 'Đánh giá thời gian nằm viện, tỷ lệ hồi phục và hiệu quả của các phương pháp điều trị.' },
            { id: 'health_3', label: 'Nhân khẩu học Bệnh nhân', icon: '👥', instruction: 'Phân tích mối liên hệ giữa tuổi, giới tính và các nhóm bệnh cụ thể.' }
        ],
        'Marketing': [
            { id: 'mkt_1', label: 'Đánh giá Hiệu quả Kênh', icon: '🎯', instruction: 'So sánh hiệu quả (ROI, CPC, Conversion Rate) giữa các kênh quảng cáo/marketing.' },
            { id: 'mkt_2', label: 'Phân tích Traffic', icon: '🌐', instruction: 'Phân tích lưu lượng truy cập theo thời gian và nguồn giới thiệu (Referral).' },
            { id: 'mkt_3', label: 'Tối ưu Ngân sách', icon: '💰', instruction: 'Đưa ra đề xuất phân bổ lại ngân sách marketing dựa trên hiệu suất thực tế của các chiến dịch.' }
        ]
    };

    return domainActions[domainInfo.domain] || defaultActions;
}
